<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{An Introduction to the blocksdesign package}
-->

# Multi-stratum nested block designs
R. N. Edmondson  
18/09/2014  

### Introduction 

Block designs group experimental units into homogeneous blocks to provide maximum precision for treatment comparisons. The most basic type of blocks are complete randomised blocks where each block contains one or more complete sets of treatments. Complete blocks estimate all treatment effects with maximum efficiency and provide excellent designs for small or medium size experiments; however for large designs, complete blocks are usually too large to provide homogeneous comparisons within the same block.

One method of reducing the variability of large complete blocks is to subdivide each complete block into smaller incomplete blocks that are fully nested within the main blocks.  Yates (1936), in an early paper on block designs, introduced a class of incomplete block designs called balanced lattice designs. These exist if the treatment number v\*v is the square of a prime  or prime power v and the nested block size is v and the number of replications is not more than v+1. For 3 or fewer replicates, lattice designs exist for any square number of treatments v\*v where the block size is v. Although balanced lattice designs have a high degree of balance and are highly efficient, their limited availability and applicability make them of limited practical value.

Following the development of resolvable balanced lattice designs, incomplete block designs were generalized in a number of ways and many other classes of incomplete block designs were introduced (see Cochran and Cox 1957). A major limitation on these early designs was that results had to be hand-calculated and a number of the early designs, such as the partially balanced incomplete block designs (PBIB) of Clatworthy (1956), were developed to simplify this analysis. However, it is now known that some PBIB designs are very inefficient for certain treatment comparisons therefore such designs are not now used. Other developments included cyclic designs for incomplete blocks, see John (1966) and John and Williams (1995). 

### Software

Incomplete block designs improve the within-blocks precision of treatment comparisons but they also confound treatment information between blocks therefore an efficient analysis must take full account of all the different sources of variability in a design when estimating treatment effects. Before the development of modern computers and modern software, the complexity of the analysis was a major restriction on the choice of incomplete block design but nowadays the availability of modern computer analysis methods such as the mixed model estimation methods available in the R packages 'lme4' (Bates et al 2014) and 'lmerTest' (Kuznetsova et al 2014) have now largely removed this restriction. Modern computer software is capable of routine analysis of very general block designs so there is now no computational limitation on the use of very general block designs.

### Algorithms

Computer algorithms for efficient block design have been extensively researched and Cook and Nachtsheim (1980) gave a review of work up to about 1980. One important development has been the use of swapping algorithms for the construction of efficient block designs for arbitrary number of treatments, arbitrary replication and arbitrary block sizes. Swapping algorithms for nested block designs work by swapping treatments at random between sets of nested blocks contained within existing blocks. Improving swaps are retained and the process is repeated until no further improvement is possible. A good general purpose swapping algorithm will give a good design close to optimal for any required design and any chosen optimality criteria. There are a number of possible choices of optimality criteria available but the most commonly used criteria are probably A-optimality, which maximizes the harmonic mean, and D-optimality, which maximizes the geometric mean of the eigenvalues of a design information matrix. Usually, the two criteria give similar though not identical results. A-optimality may have a more direct interpretation than D-optimality (John and Williams 1995 Chapter 2) but D-optimality seems to be more tractable for manipulation and optimization. 

### Block size

An important study on the effects block size on precision of estimation of treatments effects in large field trials was undertaken by Patterson and Hunter (1983). They reviewed 244 cereal variety trials arranged in generalized incomplete block designs and found that the mean improvement in yield efficiency due to the incomplete blocks was 1.43 relative to complete randomized blocks. Results varied greatly from one trial to another, however, and the distribution of efficiencies was positively skewed across the set of trials. Precision was more than doubled in one tenth of the trials and in another tenth the lattice arrangement had little effect on accuracy. Nevertheless, in half the trials the efficiency was 1.23 or more. They also modelled the background field variability of 166 of the trials assuming an empirical exponential variance function. 

Letting 2*phi(x) represent the estimated variance of the difference between two plots separated by a distance x, they calculated the semi-variance phi(x) that best fitted the observed variances of the 166 trials to be:

         phi(x) = 0.209 * (1 - 0.725 * 0.942**x)         (1)


They then considered an example design for 48 varieties in three replicate blocks and used equation (1) to estimate the theoretical variances of incomplete blocks of sizes 4, 6 or 8.They compared these estimates with the estimates from a complete randomized blocks design and used the reciprocals of the relative variances to estimate the intra-block efficiencies of the different sizes of incomplete blocks. They used these estimates to estimate  the overall efficiency of the different block sizes including inter-block information and found the estimated efficiencies of block sizes 4, 6 and 8 were 1.460, 1.523 and 1.500 respectively. They concluded that for trials with up to about 64 treatments, the nested block size should be approximately equal to the square root of the number of treatments.

Numerous other studies of block and plot sizes are available and a good source of data is the 'agridat' package by Wright (2014). 

### Simulations

The Patterson and Hunter (1983) study assumed designs with a a single nested blocks stratum and in their example analysis they assumed separate designs for each of the three block sizes 8, 6 or 4. With a nested multi-stratum block design, however, it is possible to include blocks of both size 8 and size 4 in the same design. The following table shows 20 simulations of the estimated relative efficiency of treatment comparisons for blocks of size 8 and blocks of size 4 assuming a multi-stratum nested block design with 3 replicates of 48 treatments in complete replicate blocks and with six blocks of size 8 nested in each main block and two blocks of size 4 nested in each block of size 8. The data was generated by the variance function given by Patterson and Hunter in equation (1) and the analysis was done by using the program shown in Appendix 1 based on the the 'lmerTest' package by Kuznetsa et al (2014) and the lme4 package by Bates et. al. (2014).

  
Simulation number  | Block size 8  | Block size 4    |
-------------------| --------------|-----------------|
1                  | 1.315         | 1.169           |
2                  | 1.074         | 1.130           |
3                  | 1.413         | 1.328           |
4                  | 2.559         | 2.543           |
5                  | 1.183         | 1.150           |
6                  | 1.163         | 1.128           |
7                  | 1.408         | 1.371           |
8                  | 1.721         | 1.897           |
9                  | 1.500         | 1.393           |
10                 | 2.014         | 2.141           |
11                 | 1.099         | 1.099           |
12                 | 1.431         | 1.402           |
13                 | 2.088         | 1.960           |
14                 | 2.770         | 3.096           |
15                 | 1.479         | 1.365           |
16                 | 2.465         | 2.530           |
17                 | 2.002         | 1.935           |
18                 | 1.688         | 1.971           |
19                 | 2.087         | 2.249           |
20                 | 1.114         | 1.159           |

  
The results show that the optimum block size was sometimes 8 and sometimes 4 with about equal frequency meaning that it is not possible to predict the optimum block size, even when the plot data is based on the same assumed data distribution. In real situations, the error structure will be unknown and the choice of an optimum block size will be even more problematic.  

###  Efficiency of nested blocks

In a multi-stratum nested blocks design, the choice of the smaller blocks is constrained by the fixed treatment allocation of the larger blocks therefore there could be some loss of efficiency on the smaller blocks due to the constraints of the larger blocks. Our experience is that for medium to large designs any loss of efficiency due to multi-stratum nesting is negligible. In the Patterson and Hunter example, the upper efficiency bound for blocks of size 4 is .69012 and the best achieved efficiency for blocks of size 4 in a 'classical' resolvable incomplete block design using the 'blocksdesign' package, was .68804 whereas the best achieved efficiency for hierarchically nested blocks of size 4 was .6867. Thus the loss of efficiency on blocks of size 4 in the multi-stratum nested design compared with blocks of size 4 in a 'conventional' single startum nested design was less than 0.2%. 

As a further example, a design for two replicates of 256 treatments was optimized assuming a maximal multi-stratum nesting scheme based on recursive 2-level nesting down to the minimum possible block size. The following table shows the achieved efficiencies of each blocks stratum when fitted hierarchically and when fitted as a single nested stratum in a 'classical' nested block design in resolvable main blocks. The final column shows upper bounds for each block size in a completely unconstrained block design. 
 				
  
Block numbers  | Hierarchic model | Separate models | Upper bounds|
---------------| -----------------|-----------------|-------------|
2              | 1                | 1               |1            |
4              | 0.99222          |0.99222          |0.99415      |
8              | 0.97701          |0.97701          |0.97982      |
16             | 0.94796          |0.94796          |0.95089      |
32             | 0.89474          |0.89474          |0.89474      |
64             | 0.77021          |0.77117          |0.77382      |
128            | 0.52477          |0.52603          |0.55578      |
256            | 0.01167          |0.01167          |0.25296      |

For this example, there was virtually no loss of efficiency in any stratum due to the constraints of the hierarchical model.
 
### Analysis

It was shown in the simulations for the Patterson and Hunter (1983) example that the best block size for an efficient nested block analysis is not always predictable. By using a multi-stratum design, it is possible to select the single best block size from a range of block sizes. However, it is normal when fitting data with multiple random sources of variation to select a model that includes all significant random error terms (see West et. al. 2014). So, for a large multi-stratum design with a range of block sizes a mixed model including all significant random error terms might be more appropriate than a single stratum model. Model building strategies for the inclusion or exclusion of random effects in a model have been extensively researched and the software package 'lmerTest' has an option for backward elimination of non-significant random effects from a model. 

Further discussion of model fitting is beyond the scope of this vignette and further research is needed for a better understanding of multi-stratum nested designs in large experiments. However, it is suggested that the 'blocksdesign' package provides an empirical tool that can be used to explore some of the practical aspects of multi-stratum designs. For example, as shown above, it is easy to compare the efficiency of optimized nested blocks in a multi-stratum nested block design with the efficiency of comparable optimized blocks in a design with a single level of nesting. This approach could be extended to provide power studies to compare designs with different multi-stratum nesting schemes. In the Patterson and Hunter example, there were for 3 replicates of 48 treatments so a design with four nested strata and blocks of size 48, 16, 8, 4 and 2 could easily be simulated and tested. It is important to ensure that a sufficient number of blocks is available for estimation of the stratum variances at each level of nesting and in this scheme there are 9, 18, 36 and 72 blocks for the four nested levels, which seems adequate.        

In summary, multi-stratum nesting, together with appropriate mixed model analysis of the data, has the potential for significant improvement in precision of estimation of large block designs without loss of the traditional robustness of the randomized block design. 


#### Acknowledgement

This project was partly supported by a DEFRA UK grant HH3811SX [DEFRA UK](http://randd.defra.gov.uk/Default.aspx?Menu=Menu&amp;Module=More&amp;Location=None&amp;ProjectID=12783&amp;FromSearch=Y&amp;Status=3&amp;Publisher=1&amp;SearchText=statistics&20&amp;SortString=ProjectCode&amp;SortOrder=Asc&amp;Paging=10#Description)


#### References

Alexandra Kuznetsova, Per Bruun Brockhoff and Rune Haubo Bojesen Christensen (2014). lmerTest: Tests for random and fixed effects for linear mixed effect models (lmer objects of lme4 package). R package version 2.0-6. http://CRAN.R-project.org/package=lmerTest

Bates, D., Maechler, M., Bolker, B. and Walker, S. (2014). lme4: Linear mixed-effects models using Eigen and S4. R package version 1.1-6. http://CRAN.R-project.org/package=lme4

Cook, R. D. and Nachtsheim, C. J. (1980). A comparison of algorithms for constructing exact D-optimal designs, Technometrics 22: 315-324.

Clatworthy, W. H. (1956). On partially balanced incomplete block designs with two associate classes. United States: National Bureau of Standards. Applied mathematics series 47.

Cochran, W. G. And G. M. Cox (1957) Experimental designs 2nd ed. New York: Wiley

Edmondson, R. N. (2005) Past developments and future opportunities in the design and analysis of crop experiments. The Journal of Agricultural Science, Cambridge, 143, pp 27-33
 
John, J. A. (1966) Cyclic Incomplete Block Designs, Journal of the Royal Statistical Society. Series B (Methodological), 28, 345-360

John, J. A. and Williams, E. R. (1995). Cyclic and Computer Generated Designs. Chapman and Hall, London.

Patterson H. D., Hunter E. A., (1983). The efficiency of incomplete block designs in National List and Recommended List cereal variety trials. J. Agric. Sci. Camb., 101, pp. 427-433.

R Core Team (2014). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL http://www.R-project.org/.

West, B. T., Welch, K. B., Galecki, A. T. (2014). Linear Mixed Models: A Practical Guide Using Statistical Software, Second Edition. Chapman and Hall/CRC

Wright, K. (2014). agridat: Agricultural datasets. R package version 1.9. http://CRAN.R-project.org/package=agridat

Yates, F. (1936). A new method of arranging variety trials involving a large number of varieties. Journal of Agricultural Science, Vol. 26, pp. 424-455.



#### Appendix 1: 

Simulated efficiencies for 3 replicates of 48 treatments in nested blocks of size 8 and size 4 

        Expvar = function(n = 48, s2 = .209, lambda= .725, rho = .942) {  
        V= ( diag(n)*(1-lambda) + lambda*rho**abs(row(diag(n)) -  col(diag(n))))*s2  
        crossprod(chol(V), rnorm(n))  
        }  
        library(lmerTest)
        Treatments = (c(17,20,19,35,29,34,16,31,43,28,45,6,24,41,2,37,46,15,
        27,11,33,21,5,26,1,32,14,38,8,7,10,18,48,40,13,39,23,44,47,
        30,36,22,9,3,42,25,12,4,15,29,21,30,38,42,24,34,14,17,27,7,
        33,47,41,25,1,37,35,5,36,44,8,20,48,31,2,11,13,12,28,10,45,18,4,39,
        19,6,3,26,9,46,32,40,16,22,43,23,18,46,23,37,28,35,25,15,
        30,3,24,39,33,8,32,31,16,10,19,41,26,44,42,11,13,20,21,38,4,2,22,14,
        40,6,27,47,1,29,12,36,34,9,45,17,7,43,48,5))
        blocksizes = rep(4,36)
        blocklevs = c(1,3,18,36)
        blocksmat=matrix(0,nrow = length(Treatments) , ncol = (length(blocklevs)-1))
        for (i in 1: (length(blocklevs)-1) )
        blocksmat[,i]= rep( gl(blocklevs[i+1],(blocklevs[length(blocklevs)]/blocklevs[i+1])),blocksizes)
        design=as.data.frame(cbind(blocksmat,Treatments))
        design[]=lapply(design, factor)
        colnames(design)= c("Main","Sub1","Sub2","Treatments")
        dat= matrix(data = NA, nrow = 20, ncol = 2)
        for (i in 1:20) {
        Y= c(Expvar(),Expvar(),Expvar())
        sigma=(summary(lm( Y ~ Treatments  + Main, data=design))$sigma)**2
        varmain=2*sigma/3
        BlockSize_8=lmer( Y ~ Treatments  + Main + (1|Sub1), data=design)
        BlockSize_4=lmer( Y ~ Treatments  + Main + (1|Sub2), data=design)
        lmerBlockSize_8=step(BlockSize_8, reduce.fixed = FALSE,reduce.random = FALSE, lsmeans.calc=FALSE)
        sed=lmerBlockSize_8$diffs.lsmeans.table[,2]
        dat[i,1]=varmain/mean(sed*sed)
        lmerBlockSize_4=step(BlockSize_4, reduce.fixed = FALSE, reduce.random = FALSE, lsmeans.calc=FALSE)
        sed=lmerBlockSize_4$diffs.lsmeans.table[,2]
        dat[i,2]=varmain/mean(sed*sed)
        }
        Effics=as.data.frame(round(dat,3))
        colnames(Effics)= c("Block Size 8","Block Size 4")
        
        
        
        